- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Create Nginx repo
  template:
    src: roles/nginx/templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum:
    name: nginx
    state: latest